// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// c_jam_vector
void c_jam_vector(SEXP x, const int& jam_type, const std::string& path);
RcppExport SEXP jammer_c_jam_vector(SEXP xSEXP, SEXP jam_typeSEXP, SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int& >::type jam_type(jam_typeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP);
    c_jam_vector(x, jam_type, path);
    return R_NilValue;
END_RCPP
}
// c_unjam_vector
SEXP c_unjam_vector(const std::string& path);
RcppExport SEXP jammer_c_unjam_vector(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(c_unjam_vector(path));
    return rcpp_result_gen;
END_RCPP
}
