// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// c_jam
void c_jam(SEXP x, const std::string path);
RcppExport SEXP jam_c_jam(SEXP xSEXP, SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< const std::string >::type path(pathSEXP);
    c_jam(x, path);
    return R_NilValue;
END_RCPP
}
// c_unjam
SEXP c_unjam(const std::string& path);
RcppExport SEXP jam_c_unjam(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(c_unjam(path));
    return rcpp_result_gen;
END_RCPP
}
