# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_jam <- function(x, path) {
    invisible(.Call('jamr_c_jam', PACKAGE = 'jamr', x, path))
}

c_jar <- function(x, path, append, rows_per_chunk) {
    invisible(.Call('jamr_c_jar', PACKAGE = 'jamr', x, path, append, rows_per_chunk))
}

c_unjam <- function(path) {
    .Call('jamr_c_unjam', PACKAGE = 'jamr', path)
}

c_unjar <- function(path, chunks) {
    .Call('jamr_c_unjar', PACKAGE = 'jamr', path, chunks)
}

