# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_jam_vector <- function(x, jam_type, path) {
    invisible(.Call('jammer_c_jam_vector', PACKAGE = 'jammer', x, jam_type, path))
}

c_unjam_vector <- function(path) {
    .Call('jammer_c_unjam_vector', PACKAGE = 'jammer', path)
}

